### ISSUE TITLE
Error when adding a twitter account

### ISSUE THREAD

**Issue by Mara-Li** [libertyernie/CrosspostSharp#30]
Hello ! Error code "NullReferenceException" when I add my twitter account.
"Object not set to instance of Object"
Can you help me with that ? Thanks !

This application is perfect however !

**Comment by libertyernie** [comment]
https://github.com/linvi/tweetinvi/issues/850#issuecomment-494746515

I'll fix this in the next release.

**Comment by libertyernie** [comment]
3.6rc1 should work:
https://github.com/libertyernie/CrosspostSharp/releases/tag/v3.6rc1
