### ISSUE TITLE
don't connect to DA

### ISSUE THREAD

**Issue by Mara-Li** [libertyernie/CrosspostSharp#31]
Don't connect to DA since the DA update with the new theme. I don't know how to use the json for add it manually.

**Comment by libertyernie** [comment]
I've been having this problem too, with scraps. I'll keep an eye on it and see if there's a way to fix it.

**Comment by Mara-Li** [comment]
Well, how can i add "manually" the DA ? I use your release, not the manual compilation.

**Comment by libertyernie** [comment]
I haven't figured out how to fix it yet, but I'll make a new release when I do.

**Comment by Mara-Li** [comment]
Hello, you're new release don't help this problem, it's normal ?

**Comment by libertyernie** [comment]
It works for me. Could you post a screenshot of the error or something?

**Comment by Mara-Li** [comment]
https://imgur.com/xsqIqEg
I take a gif, it's better than explain, because of my bad english ^^. It does the same with Eclipse or not.

**Comment by libertyernie** [comment]
Thanks, that helps! I'll look into it maybe this weekend.

**Comment by libertyernie** [comment]
Should be fixed in 3.7.1 - let me know if it still doesn't work.

**Comment by Mara-Li** [comment]
Working ! Thanks
